version: "3.9"

services:
  wander-dev:
    build:
      context: ../frontend/wander
      dockerfile: Dockerfile.dev
    image: wander-dev:latest
    container_name: wander-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-dev.rule=Host(`wander.localhost`)"
      - "traefik.http.services.wander-dev.loadbalancer.server.port=3000"
    networks:
      - traefik-network

  reggie-dev:
    build:
      context: ../frontend/reggie
      dockerfile: Dockerfile.dev
    image: reggie-dev:latest
    container_name: reggie-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reggie-dev.rule=Host(`reggie.localhost`)"
      - "traefik.http.services.reggie-dev.loadbalancer.server.port=3002"
    networks:
      - traefik-network
