version: "3.9"

services:
  wander-dev:
    build:
      context: ../frontend/wander
      dockerfile: Dockerfile.dev
    image: wander-dev:latest
    container_name: wander-dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-dev.rule=Host(`www.wander.com`) && PathPrefix(`/wander`)"
      - "traefik.http.services.wander-dev.loadbalancer.server.port=3000"
    networks:
      - traefik-network
    env_file:
      - ../frontend/wander/.env  # Path to your .env file
    volumes:
      - ../frontend/wander:/app  # Mount the entire app directory, not just src
    ports:
      - "3000:3000"  # Expose the port to access the app locally
    command: "npm run dev"  # Ensure you're running Next.js in dev mode to watch for changes

networks:
  traefik-network:
    external: true
