api:
  dashboard: true
  insecure: false # Secures the dashboard

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  middlewares:
    shared-cookie-headers:
      headers:
        forwardedHeaders:
          - Cookie
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    redirect-http:
      entryPoints:
        - web
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - redirect-to-https
      service: noop

services:
  noop:
    loadBalancer:
      servers:
        - url: "http://127.0.0.1" # Placeholder for redirection
